menu:
  '文章': /
  '归档': /archives/
  '微博': http://weibo.com/333241589
  'Github': https://github.com/wenpengfei
  # '500px': https://500px.com/catwen
  Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga:

# Copyright Infomation
startyear: 2015
